name: size

on:
    pull_request:
        branches: [master]

jobs:
    size:
        runs-on: ubuntu-latest

        permissions:
            pull-requests: write

        steps:
            - uses: actions/checkout@v3

            - uses: pnpm/action-setup@v2
              with:
                  version: 7

            - uses: pajecawav/tiny-file-size-action@v1
              with:
                  github_token: ${{ secrets.GITHUB_TOKEN }}
                  globs: "dist/*.{js,ts}"
